1 iteration task №10
druzhininyury/yandex-workshop-registration-service pull request #6
Opened 2024-11-26 04:37 UTC by DTF98

2024-11-26 08:20 UTC, Hyacintholuscus commented on src/main/java/ru/practicum/workshop/registrationservice/controller/RegistrationController.java
> +    public PublicRegistrationCountDto countByStatus(@RequestParam("eventId") @Positive Long eventId, @RequestParam("status") String status) {
Это больше вопрос к ТЗ: "Добавить эндпоинт, возвращающий количество заявок в разных статусах по eventId". Я могла бы интерпретировать это как вернуть DTO:
PENDING: n заявок
APPROVED: m заявок
и так далее

2024-11-26 08:24 UTC, Hyacintholuscus commented on src/main/java/ru/practicum/workshop/registrationservice/mapping/RegistrationMapper.java
> +//    @Mapping(target = "", source = "registrationStatus", ignore = true)
Закомментированный код можно удалить

2024-11-26 08:26 UTC, Hyacintholuscus commented on src/main/resources/db/migration/V1__initial_schema.sql
> +    registration_status VARCHAR(64) NOT NULL,
Эти изменения нужно вынести в отдельный файл V2__название_миграции.sql

2024-11-26 08:31 UTC, Hyacintholuscus commented on src/main/java/ru/practicum/workshop/registrationservice/repository/RegistrationRepository.java
> +    @Query(value = "SELECT * FROM registrations WHERE registration_status = :status ORDER BY created_at ASC LIMIT 1", nativeQuery = true)
Думаю, тут можно использовать не nativeQuery, а JPQL, так как в этом запросе не вижу ничего специфичного для базы данных

2024-11-26 08:37 UTC, Hyacintholuscus commented on src/main/java/ru/practicum/workshop/registrationservice/service/RegistrationServiceImpl.java
> +        newRegistration.setCreatedAt(LocalDateTime.now());
Заполнение этих полей можно в маппере производить, например:
Добавить в аннотации Mapper соответствующие импорты - Mapper(imports = {LocalDateTime.class})
В аннотации Mapping(target  "createdAt", expression = "java(LocalDateTime.now())")

2024-11-26 08:45 UTC, Hyacintholuscus commented on src/main/java/ru/practicum/workshop/registrationservice/service/RegistrationServiceImpl.java
> +            if (waitingRegistration.isPresent()) {
Думаю, тут можно было бы использовать .OrElseGet() для Optional. Это просто информация на будущее

2024-11-26 08:47 UTC, Hyacintholuscus commented on src/main/java/ru/practicum/workshop/registrationservice/model/Registration.java
> +    private String registrationStatus;
Почему тип поля String, а не RegistrationStatus?

2024-11-26 08:51 UTC, Hyacintholuscus commented on src/main/java/ru/practicum/workshop/registrationservice/service/RegistrationServiceImpl.java
> +        if (updateStatusDto.getStatus().equals(RegistrationStatus.REJECTED.toString())) {
Эту проверку надо делать до сохранения изменений в БД

2024-11-26 09:02 UTC, Hyacintholuscus commented on src/main/java/ru/practicum/workshop/registrationservice/service/RegistrationServiceImpl.java
> +                .filter(r -> statusesFromRequest.contains(RegistrationStatus.parseStatus(r.getRegistrationStatus())))
Можно сделать запрос для поиска регистраций с конкретными статусами, чтобы из БД возвращались только искомые регистрации

2024-11-26 09:04 UTC, Hyacintholuscus commented on src/main/resources/db/migration/V1__initial_schema.sql
> +    registration_status VARCHAR(64) NOT NULL,
В БД можно поставить ограничение на registration_status, что значения должны соответствовать тем статусам, которые могут быть в приложении. Но это просто к сведению

2024-11-26 09:15 UTC, Hyacintholuscus requested changes
Хорошая работа. Но есть моменты, которые надо подкорректировать. И нет тестов для новых эндпоинтов

2024-11-26 13:55 UTC, DTF98 commented on src/main/resources/db/migration/V1__initial_schema.sql
> +    registration_status VARCHAR(64) NOT NULL,
Я это прекрасно знаю, но захотелось в коде это обработать, так как я на ошибку могу влияние оказывать более точно и валидация какая-никакая есть, а до бд валидацию тянуть не очень круто, там вообще логики должно быть минимум.

2024-11-27 04:35 UTC, DTF98 commented on src/main/java/ru/practicum/workshop/registrationservice/model/Registration.java
> +    private String registrationStatus;
https://habr.com/ru/articles/757212/

Енам не оч популярен для баз данных, особенно в проде... От него могут быть проблемы не дистанции)

2024-11-27 04:35 UTC, DTF98 commented on src/main/resources/db/migration/V1__initial_schema.sql
> +    registration_status VARCHAR(64) NOT NULL,
Я тебе ссылку почитать кинул снизу про всю эту историю

2024-11-27 15:20 UTC, merged

2024-12-08 23:50 UTC, druzhininyury commented on src/main/java/ru/practicum/workshop/registrationservice/model/Registration.java
> +    private String registrationStatus;
Спринг прекрасно работает и без перечислений в БД. Вот ставишь такую аннотацию:
@Enumerated(EnumType.STRING)
и спринг сам конвертирует в строку.